version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: asatrya/json_server:1.0
    networks:
      - internal
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

networks:
  internal:
    driver: bridge